Add Components
lilyfrancis/MathMagicians pull request #2
Opened 2021-10-29 14:41 UTC by lilyfrancis

This is a React project, In this section, I added a calculator component

2021-10-29 15:38 UTC, henatan99 requested changes
Hi @lilyfrancis , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] In this milestone you are expected to delete boiler plate files in both the public and src folders (images, logos, and icons). :pray: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-29 15:38 UTC, henatan99 commented on src/App.js
> -      <header className="App-header">
- [ ] In this milestone you are requested to make the `App` component a React class-based component. It is the objective's milestone. Kindly refactor it. :pray:

2021-10-29 15:38 UTC, henatan99 commented on src/components/Calculator.js
> +    <div className="container">
- [ ] In this milestone you are requested to make the `Calculator` component a React class-based component. It is the objective's milestone. Kindly refactor it. :pray:

2021-10-30 00:56 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello @lilyfrancis, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-30 08:50 UTC, merged